export const {
    NEXT_PUBLIC_API_URL: API_URL,
    NEXT_PUBLIC_IV_LENGTH: IV_LENGTH,
    NEXT_PUBLIC_AES_METHOD: AES_METHOD,
    NEXT_PUBLIC_PASSWORD: SECRET_KEY,
    MONGODB_URI: MONGODB_URI,
} = process.env;
